version: '3'

services:
  simplycode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    hostname: simplycode.local
  