---
# This workflow tests that the generated HTML file and the main index contain
# the same content. Even though `diff` is told to ignore whitespace, it will
# fail if a comma is placed on a newline. `sed` is used to remove all newlines
# that are followed by a comma, before running `diff`.
name: Compare generated and index HTML

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'www/api/data/generated.html'
      - 'www/index.html'
  push:
    paths:
      - 'www/api/data/generated.html'
      - 'www/index.html'

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: diff
        run: |
          diff \
            --ignore-all-space \
            --ignore-blank-lines \
            --label='www/api/data/generated.html' \
            --report-identical-files\
            --unified=0 \
            <(cat www/api/data/generated.html | sed -zE 's/\n\s+,/,/g') \
            www/index.html
